n=int(input("So tien ban dau: "))
k=int(input("SO thang gui: "))
t=float(input("Lai suat/ thang: "))
m=n*(1+k*t)
print("Voi so tien ban dau {}, sau {} thang gui, lai suat {}/thang".format(n,k,t))
print("Thi so tien nhan duoc cuoi ky la:",m)